replicaCount: 1

serviceAccount:
  create: true
  name: ""
  annotations: {}

image:
  repository: peachflavor/my-ipa-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  host: "localhost"
  path: "/"
  pathType: "Prefix"