# my-ipa-app-chart/values.yaml
replicaCount: 1

image:
  repository: peachflavor/my-ipa-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
  host: "localhost"
  path: "/"
  pathType: "Prefix"

# Add readiness/liveness probes
probes:
  enabled: true
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 5