name: Deploy to Kubernetes
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./my-ipa-app
        push: true
        tags: peachflavor/my-ipa-app:latest

    # Create a kind cluster
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.5.0
      with:
        cluster_name: kind
        wait: 120s

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.12.3'  # Specifying a newer version of Helm

    # Optional: verify cluster connection
    - name: Verify Kubernetes connection
      run: kubectl cluster-info

    # Create namespace first
    - name: Create namespace
      run: |
        kubectl create namespace default || true

    - name: Deploy to Kubernetes
      run: |
        helm version
        helm upgrade --install my-ipa-app ./my-ipa-app-chart \
          --namespace default \
          --wait \
          --timeout 5m

    - name: Test Service (Port Forward)
      run: |
        # Start port forwarding in the background
        kubectl port-forward svc/my-ipa-app 8080:80 &
        # Wait for port forwarding to be ready
        sleep 5
        # Test the connection
        curl http://localhost:8080
        # Show the response in the logs
        echo "Response from service:"
        curl -s http://localhost:8080

    - name: Test Ingress
      run: |
        # Get Ingress IP
        INGRESS_IP=$(kubectl get ingress my-ipa-app-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        echo "Ingress IP: $INGRESS_IP"
        # Add hostname to /etc/hosts
        echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts
        # Test the connection through ingress
        curl -H "Host: localhost" http://localhost
